### PR TITLE
EVG-15372 add FTDC format check

### PR DESCRIPTION
**Pull request by ybrill**
Implement https://github.com/evergreen-ci/cedar/pull/380#discussion_r701953667

### CODE REVIEW

**Review by julianedwards — APPROVED** [review]
LGTM % fixing the tests (probably just need to set the artifact format to FTDC).

**Comment by julianedwards** [comment]
Actually, let's hold off on merging this. It looks like artifact formats are getting set incorrectly to `text` instead of `ftdc`.

**Comment by ybrill** [comment]
> artifact formats are getting set incorrectly to text instead of ftdc

@julianedwards Should I open a TIPS ticket for the file type to be set correctly? Or should we just leave it

**Comment by julianedwards** [comment]
I spoke to Alex, I think the best thing to do for now is change this [line](https://github.com/evergreen-ci/cedar/blob/main/model/perf.go#L651) to check for raw events schema instead of type, as done [here](https://github.com/evergreen-ci/cedar/blob/main/rpc/internal/perf_service.go#L263).

**Review by julianedwards — APPROVED** [review]

**Pull request merged**
