### PR TITLE
EVG-8432: Evergreen Fix perf_test.go in cedar

### PR DESCRIPTION
**Pull request by ancostas**

### CODE REVIEW

**Comment by Kimchelly** [comment]
This should already be fixed by #243.

**Comment by ancostas** [comment]
@Kimchelly That still seems to be open. In any case, if you all are happy handling it on your end, go ahead and reassign the ticket and close this.

**Comment by Kimchelly** [comment]
I just merged it so we should be good to close EVG-8432.

**Comment by ancostas** [comment]
@Kimchelly Thx!

**Pull request closed without merging**
